---
name: CI

on:
  workflow_call:
    inputs:
      java_version:
        description: Java version to use
        type: string
        required: false
        default: 11
      publish_snapshots:
        description: Whether to attempt publishing snapshots. When false, the workflow will only run build.
        type: boolean
        default: false
        required: false
    secrets:
      ossrh_username:
        required: true
      ossrh_password:
        required: true
      ossrh_signing_key:
        required: false
      ossrh_signing_password:
        required: false
      sonar_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}
          cache: 'maven'
          server-id: sonatype-nexus-snapshots
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.ossrh_signing_key }}
          gpg-passphrase: OSSRH_SIGNING_PASSWORD

      - name: build
        run: mvn --batch-mode --update-snapshots -P IT,sonar verify

      - name: publish-snapshots
        if: inputs.publish_snapshots && github.repository_owner == 'jqassistant-plugin' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: mvn deploy --batch-mode -P release
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
