---
name: CI

on:
  workflow_call:
    inputs:
      java_version:
        description: Java version to use for running Sonar and publishing docs & artifacts
        type: string
        required: false
        default: 17
      java_test_versions:
        description: Java versions to use for testing the project
        type: string
        required: false
        default: '[11, 17, 21]'
      publish_snapshots:
        description: Whether to attempt publishing snapshots. When false, the workflow will only run build.
        type: boolean
        default: true
        required: false
      pages:
        description: Path expression for GitHub pages to upload.
        type: string
        required: false
    secrets:
      ossrh_username:
        required: true
      ossrh_password:
        required: true
      ossrh_signing_key:
        required: false
      ossrh_signing_password:
        required: false
      sonar_token:
        required: true

permissions:
  contents: write

jobs:
  build:
    name: Build with java ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: ${{ fromJson(inputs.java_test_versions) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ts-graphviz/setup-graphviz@v1
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java_version }}
          cache: 'maven'
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          sonatypeSnapshots: true
      - name: Build and test with Java ${{ matrix.java_version }}
        run: mvn --batch-mode --update-snapshots -P IT install

      - name: Deploy GitHub Pages to snapshot
        if: ${{ inputs.pages != '' }} && ${{ matrix.java_version }} == ${{ inputs.java_version }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.pages }}
          destination_dir: ./snapshot
          keep_files: true

      - name: Execute SonarCloud analysis
        run: |
          if [ ${{ matrix.java_version }} == ${{ inputs.java_version }} ]; then
            mvn --batch-mode -P sonar sonar:sonar
          fi
        env:
          SONARCLOUD_LOGIN: ${{ secrets.SONAR_TOKEN }}

  publish-snapshots:
    runs-on: ubuntu-latest
    needs: build
    if: contains(fromJSON('["buschmais", "jqassistant-plugin", "jqassistant-tooling", "jQAssistant"]'), github.repository_owner) && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: ts-graphviz/setup-graphviz@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}
          cache: 'maven'
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          sonatypeSnapshots: true
          servers: |
            [{
              "id": "sonatype-nexus-snapshots",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_PASSWORD }}"
            }]          
      - name: publish-snapshots
        run: mvn deploy --batch-mode -DskipTests
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
