---
name: release

on:
  workflow_call:
    inputs:
      java_version:
        description: Java version to use
        type: string
        required: false
        default: 17
      branch:
        description: "The branch to checkout when cutting the release."
        type: string
        required: true
      releaseVersion:
        description: "Default version to use when preparing a release."
        type: string
        required: true
      developmentVersion:
        description: "Default version to use for new local working copy."
        type: string
        required: true
      dryRun:
        description: "Perform a dry run"
        required: true
        default: 'false'
        type: string
      artifacts:
        description: "Path expression for artifacts to upload."
        type: string
        required: true
        default: ""
    secrets:
      ossrh_username:
        required: true
      ossrh_password:
        required: true
      ossrh_signing_key:
        required: true
      ossrh_signing_password:
        required: true
      sonar_token:
        required: true

jobs:
  release:
    name: Release on Sonatype OSS
    if: contains(fromJSON('["buschmais", "jqassistant-plugin", "jqassistant-tooling", "jQAssistant"]'), github.repository_owner)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - uses: ts-graphviz/setup-graphviz@v1

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}
          cache: 'maven'
          server-id: sonatype-nexus-staging
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_SIGNING_KEY }}
          gpg-passphrase: OSSRH_SIGNING_PASSWORD

      - name: Prepare and perform release
        run: mvn release:prepare release:perform -ntp --batch-mode -DreleaseVersion=${{ inputs.releaseVersion }} -DdevelopmentVersion=${{ inputs.developmentVersion }} -DdryRun=${{ inputs.dryRun }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
          SONARCLOUD_LOGIN: ${{ secrets.SONAR_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.releaseVersion }}
#        tag_name: ${{ github.event.inputs.releaseVersion }}
          draft: true
          files: ${{ inputs.artifacts }}
          token: ${{ secrets.GITHUB_TOKEN }}


#      - name: Upload Artifacts
#        if: ${{ inputs.artifacts != '' }}
#        uses: actions/upload-artifact@v4
#        with:
#           name: artifacts
#           path: |
#             ${{inputs.artifacts}}
#           if-no-files-found: error

