---
name: Release Drafter

on:
  workflow_call:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  update_release_draft:
    if: contains(fromJSON('["buschmais", "jqassistant-plugin", "jqassistant-tooling", "jQAssistant"]'), github.repository_owner)
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: release-drafter
        uses: release-drafter/release-drafter@v6
        with:
          _extends: jqassistant-tooling/jqassistant-github-actions/.github/workflows/release-drafter.yml@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}