---
name: Release Drafter

on:
  workflow_call:
    inputs:
      _extends:
        description: "Path expression for the release drafter configuration file."
        type: string
        required: true
    secrets:
      gh_token:
        required: true
  push:
    branches:
      - master
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  update_release_draft:
    if: contains(fromJSON('["buschmais", "jqassistant-plugin", "jqassistant-tooling", "jQAssistant"]'), github.repository_owner)
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: release-drafter
        uses: release-drafter/release-drafter@v6
        with:
          _extends: ${{ inputs._extends }}
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}