---
name: release

on:
  workflow_call:
    inputs:
      java_version:
        description: Java version to use
        type: string
        required: false
        default: 17
      branch:
        description: "The branch to checkout when cutting the release."
        type: string
        required: true
      releaseVersion:
        description: "Default version to use when preparing a release."
        type: string
        required: true
      developmentVersion:
        description: "Default version to use for new local working copy."
        type: string
        required: true
      dryRun:
        description: 'Whether to perform a dry run'
        required: true
        default: 'false'
        type: boolean
    secrets:
      ossrh_username:
        required: true
      ossrh_password:
        required: true
      ossrh_signing_key:
        required: true
      ossrh_signing_password:
        required: true
      sonar_token:
        required: true

jobs:
  dry-run:
    if: ${{ github.event.inputs.dryRun }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Maven Dry Run
        run: mvn --dry-run release:prepare

  release:
    needs: dry-run
    if: ${{ success() && github.event.inputs.dryRun == 'false' }}
    uses: jqassistant-tooling/jqassistant-github-actions/.github/workflows/release.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
      developmentVersion: ${{ github.event.inputs.developmentVersion }}
    secrets:
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
