---
name: SDKMAN Release Candidate

on:
  workflow_dispatch:
    inputs:
      candidate:
        description: "Candidate ID."
        type: string
        required: true
      version:
        description: "Version of the candidate."
        required: true
      url:
        description: "URL of the candidate."
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: https://github.com/sdkman/sdkman-release-action/
          path: sdkman-release-action
      - uses: ./sdkman-release-action
        with:
          CANDIDATE: ${{ github.event.inputs.candidate }}
          VERSION: ${{ github.event.inputs.version }}
          URL: ${{ github.event.inputs.url }}
          CONSUMER-KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
          CONSUMER-TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}

