---
name: SDKMAN Set Default Candidate

on:
  workflow_dispatch:
    inputs:
      candidate:
        description: "Candidate ID."
        type: string
        required: true
      version:
        description: "Default version of the candidate."
        required: true

jobs:
  set-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: sdkman/sdkman-default-action
          path: sdkman-default-action
      - uses: ./sdkman-default-action
        with:
          CANDIDATE: ${{ github.event.inputs.candidate }}
          VERSION: ${{ github.event.inputs.version }}
          CONSUMER-KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
          CONSUMER-TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}

